### PR TITLE
compilation fixes

### PR DESCRIPTION
**Pull request by mtaillefumier**
- Fix for building errors introduced by https://github.com/cp2k/cp2k/pull/1985
- fix the toolchain when building spla. Should fix the issue with the dashboard

### CODE REVIEW

File: tools/toolchain/scripts/stage8/install_spla.sh [hunk 1]
```diff
@@ -195,9 +196,11 @@ EOF
 export SPLA_CFLAGS="${SPLA_CFLAGS}"
 export SPLA_LDFLAGS="${SPLA_LDFLAGS}"
 export SPLA_CUDA_LDFLAGS="${SPLA_CUDA_LDFLAGS}"
+export SPLA_HIP_LDFLAGS="${SPLA_HIP_LDFLAGS}"
 export CP_DFLAGS="\${CP_DFLAGS} IF_MPI(-D__SPLA|)"
 export CP_CFLAGS="\${CP_CFLAGS} ${SPLA_CFLAGS}"
-export CP_LDFLAGS="\${CP_LDFLAGS} IF_CUDA(${SPLA_CUDA_LDFLAGS}|${SPLA_LDFLAGS})"
+export CP_LDFLAGS="\${CP_LDFLAGS} IF_HIP(
+${SPLA_HIP_LDFLAGS}|IF_CUDA(${SPLA_CUDA_LDFLAGS}|${SPLA_LDFLAGS}))"
```
Comment (oschuett) [inline tools/toolchain/scripts/stage8/install_spla.sh]: I believe those two lines ought to be one.

**Comment by oschuett** [comment]
The failed precommit check is on me. I'll restart it once #1993 is merged.

**Comment by mtaillefumier** [comment]
> The failed precommit check is on me. I'll restart it once #1993 is merged.

it happens.  a parenthesis was missing that's why the compilation failed with cuda.
