### ISSUE TITLE
Build breaks on FreeBSD: undefined reference to `dfftw_plan_with_nthreads_'

### ISSUE THREAD

**Issue by yurivict** [cp2k/cp2k#12]
```VERSION=ssmp``` fails to build on FreeBSD 11.2:

```
/usr/ports/science/cp2k/work/cp2k-6.1/lib/FreeBSD-libint-gfortran/ssmp/libcp2kfft.a(fftw3_lib.o): In function `__fftw3_lib_MOD_fftw3_create_plan_3d':
fftw3_lib.F90:(.text+0x1191): undefined reference to `dfftw_plan_with_nthreads_'
collect2: error: ld returned 1 exit status
gmake[5]: *** [/usr/ports/science/cp2k/work/cp2k-6.1/obj/FreeBSD-libint-gfortran/ssmp/all.dep:129: /usr/ports/science/cp2k/work/cp2k-6.1/exe/FreeBSD-libint-gfortran/cp2k_she
```

```VERSION=sopt``` builds fine.

Version 6.1

**Comment by alazzaro** [comment]
SMP version requires OpenMP FFTW library. You should link with

-lfftw3 -lfftw3_omp

(libfftw3_threads)

**Comment by yurivict** [comment]
It takes libraries from ```arch/FreeBSD-libint-gfortran.ssmp```.

**Comment by yurivict** [comment]
https://github.com/cp2k/cp2k/pull/13

**Comment by alazzaro** [comment]
Those arch files are ancient and probably never tested... Thanks for the patch.
However, we cannot accept PR (not yet, we are working on that) since github is just the mirror of the sourceforce SVN repo. I will make the changes there...

**Comment by yurivict** [comment]
> I will make the changes there...

As long as they land into the repository.

**Comment by yurivict** [comment]
BTW, I've tested the arch files in the FreeBSD port, they all work fine.

**Comment by alazzaro** [comment]
I can assume that you have a newer version of the GCC 4.6, right? The comment in the file is mentioning a quite old thread on GNU bugzilla (>10 yo!)

**Comment by yurivict** [comment]
> I can assume that you have a newer version of the GCC 4.6, right?

I override ```CC``` with ```cc``` command, which is clang-6.0.1, and it builds fine.

**Comment by alazzaro** [comment]
OK, I have updated the FreeBSD arch files for SOPT, SSMP, POPT, and PSMP. I have removed the specific libint arch files.

**Comment by yurivict** [comment]
> OK, I have updated the FreeBSD arch files for SOPT, SSMP, POPT, and PSMP.

Thanks!

> I have removed the specific libint arch files.

So how are libint libraries specified now?

**Comment by alazzaro** [comment]
Well, the files in the arch directory are only there as a starting point, such that the users can make their own configurations based on the instruction of the [INSTALL](https://github.com/cp2k/cp2k/blob/master/cp2k/INSTALL) file. LIBINT is just one of the possible libraries. Clearly, we cannot add all possible combinations of libraries in the arch directory...
The current arch files for FreeBSD are the minimal configuration to get CP2K compiled. I can suggest two solutions:
1) You change your files to include Libint in your local version
2) We add Libint and Libxc to the current configuration, since this is the most tested configuration in the CP2K regtests (see https://dashboard.cp2k.org/ )
