### ISSUE TITLE
cp2k 2023.2 build failure

### ISSUE THREAD

**Issue by chenrui333** [cp2k/cp2k#2950]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
 /private/tmp/cp2k-20230827-28034-a3hxu0/cp2k-2023.2/exe/Darwin-gfortran/cp2k.ssmp cp2k.o  -lcp2kstart -lcp2kmc -lcp2kswarm -lcp2kmotion -lcp2kthermostat -lcp2kemd -lcp2ktmc -lcp2kmain -lcp2kdbt -lcp2ktas -lcp2kdbm -lcp2kgrid -lcp2kgriddgemm -lcp2kgridcpu -lcp2kgridref -lcp2kgridcommon -ldbcsrarnoldi -ldbcsrx -lcp2kshg_int -lcp2keri_mme -lcp2kminimax -lcp2khfxbase -lcp2ksubsys -lcp2kxc -lcp2kao -lcp2kpw_env -lcp2kinput -lcp2kpw -lcp2kgpu -lcp2kfft -lcp2kfpga -lcp2kfm -lcp2kcommon -lcp2koffload -lcp2kmpiwrap -lcp2kbase -L/private/tmp/cp2k-20230827-28034-a3hxu0/cp2k-2023.2/lib/Darwin-gfortran/ssmp/exts/dbcsr -ldbcsr -L/opt/homebrew/opt/fftw/lib -lfftw3 -lfftw3_threads -lstdc++ -framework Accelerate -L/opt/homebrew/opt/libxc/lib -lxcf03 -lxc -L/opt/homebrew/Cellar/cp2k/2023.2/libexec/lib -lint2
Undefined symbols for architecture arm64:
  "_libint2_build_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_eri1 in libcp2kmain.a(libint_wrapper.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[3]: *** [/private/tmp/cp2k-20230827-28034-a3hxu0/cp2k-2023.2/exe/Darwin-gfortran/libcp2k_unittest.ssmp] Error 1
make[3]: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_libint2_build_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_2eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eris in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_3eri_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_build_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_get_derivs in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_cleanup_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_cleanup_eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_2eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_2eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_3eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_3eri1 in libcp2kmain.a(libint_wrapper.o)
  "_libint2_init_eri1", referenced from:
      ___libint_wrapper_MOD_cp_libint_init_eri1 in libcp2kmain.a(libint_wrapper.o)
ld: symbol(s) not found for architecture arm64
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5692000123/job/15428333003
my local build log (ventura arm), https://gist.github.com/chenrui333/55cfeb72d0f8087dcd1e1d9b47587848
relates to Homebrew/homebrew-core#137880

**Comment by mkrack** [comment]
Did you check [this HowTo](https://www.cp2k.org/howto:compile_on_macos)?

**Comment by fxcoudert** [comment]
We did, and have built cp2k in Homebrew for several years now. More specifically, the exact same build process was working in 2023.1 and is now failing with 2023.2

I couldn't find any reference to libint in the 2023.2 release notes, is there a change in the requirements there? We build cp2k against libint-v2.6.0-cp2k-lmax-5 from https://github.com/cp2k/libint-cp2k/releases/download/v2.6.0/libint-v2.6.0-cp2k-lmax-5.tgz which seems to be the latest version available

**Comment by mkrack** [comment]
To the best of my knowledge, nothing has changed with respect to libint 2.6.0 in 2023.2. The macOS Apple M1 regression test works for 2023.2, but, note, that `gcc@12` is used instead of the default GCC 13 in the corresponding [arch file](https://github.com/cp2k/cp2k/blob/master/arch/Darwin-gnu-arm64.psmp#L32).

**Comment by fxcoudert** [comment]
Hum, not sure what happened, but a re-run on our CI worked this time (https://github.com/Homebrew/homebrew-core/pull/141288). Intermittent linking error seems like a weird thing, but hey, it built on all machines this time. Maybe a new version of something fixed it.

This can be closed.
